const Images = {
  profileImage: require('../../../assets/images/profilePicture.jpeg'),
  bImage1: require('../../../assets/images/bImage1.jpeg'),
  bImage2: require('../../../assets/images/bImage2.jpeg'),
  bImage3: require('../../../assets/images/bImage3.webp'),
  bImage4: require('../../../assets/images/bImage4.webp'),
  bImage5: require('../../../assets/images/bImage5.webp'),
  gImage1: require('../../../assets/images/gImage1.jpeg'),
  gImage2: require('../../../assets/images/gImage2.jpeg'),
  gImage3: require('../../../assets/images/gImage3.jpeg'),
  gImage4: require('../../../assets/images/gImage4.webp'),
  gImage5: require('../../../assets/images/gImage5.jpeg'),
  gImage6: require('../../../assets/images/gImage6.webp'),
  notification_icon: require('../../../assets/images/notification_icon.png'),
  left_back_arrow: require('../../../assets/images/left_back_arrow.png'),
  vans_boy_image: require('../../../assets/images/vans_boy_image.png'),
  vans_season_image: require('../../../assets/images/vans_season_image.png'),
  progress_image: require('../../../assets/images/Progress_image.png'),
  golden: require('../../../assets/images/golden.png'),
  locked: require('../../../assets/images/locked.png'),
  drops_collection: require('../../../assets/images/drops_collection.png'),
  rubius_image: require('../../../assets/images/rubius_image.png'),
  coscu_image: require('../../../assets/images/coscu_image.png'),
  slakun10_image: require('../../../assets/images/slakunto_image.png'),
  detail_icon: require('../../../assets/images/detail_icon.png'),
};
export default Images;
